name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  cupertino_icons: ^1.0.8
  confetti: ^0.8.0
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  http: ^1.1.0
  rive: ^0.13.20
  fl_chart: ^1.1.1
  shared_preferences: ^2.3.2

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:

    - assets/Starting.png
    - assets/trust.png
    - assets/Ass.png
    - assets/cloud_top.png
    - assets/cloud_bottom.png
    - assets/KumbhSans-VariableFont_YOPQwght.ttf
    - assets/greet.png
    - assets/numbers.png
    - assets/food.png
    - assets/travel.png
    - assets/guess.png
    - assets/flash-card.png
    - assets/picture-learning.png
    - assets/quizzes.png
    - assets/history.png
    - assets/culture.png
    - assets/tour.png
    - assets/food-c.png
    - assets/home.png
    - assets/card.png
    - assets/mic.png
    - assets/quiz.png
    - assets/shopping.png
    - assets/emergency.png
    - assets/polite.png
    - assets/techno.png
    - assets/respect.png
    - assets/weather.png
    - assets/feeling.png
    - assets/fav.png
    - assets/charity.png
    - assets/boy.png
    - assets/correct.mp3
    - assets/unity.png
    - assets/confetti.mp3
    - assets/discipline.png
    - assets/easy.png
    - assets/intermediate.png
    - assets/hard.png
    - assets/assessments.png
    - assets/common.png
    - assets/intermediate-level 1.png
    - assets/sun.png
    - assets/moon.png
    - assets/rain.png
    - assets/cloud.png
    - assets/star.png
    - assets/wind.png
    - assets/tree.png
    - assets/flower.png
    - assets/river.png
    - assets/mountain.png
    - assets/fish.png
    - assets/bird.png
    - assets/dog.png
    - assets/cat.png
    - assets/house.png
    - assets/patience.png
    - assets/car.png
    - assets/book.png
    - assets/phone.png
    - assets/clock.png
    - assets/food1.png
    - assets/storm.png
    - assets/earthquake.png
    - assets/volcano.png
    - assets/tsunami.png
    - assets/computer.png
    - assets/internet.png
    - assets/plane.png
    - assets/hospital.png
    - assets/university.png
    - assets/government.png
    - assets/thunder.png
    - assets/humility.png
    - assets/grass.png
    - assets/leaf.png
    - assets/bridge.png
    - assets/boat.png
    - assets/ant.png
    - assets/farmer.png
    - assets/wisdom.png
    - assets/strength.png
    - assets/shadow.png
    - assets/noise.png
    - assets/love.png
    - assets/darkness.png
    - assets/lightning.png
    - assets/hunger.png
    - assets/smile.png
    - assets/problem.png
    - assets/answer.png
    - assets/forest.png
    - assets/village.png
    - assets/town.png
    - assets/dream.png
    - assets/peace.png
    - assets/neighbor.png
    - assets/help.png
    - assets/dignity.png
    - assets/obsession.png
    - assets/sacred.png
    - assets/heritage.png
    - assets/privilege.png
    - assets/despair.png
    - assets/harmony.png
    - assets/ambition.png
    - assets/consequences.png
    - assets/betrayal.png
    - assets/burden.png
    - assets/mystery.png
    - assets/abundance.png
    - assets/obligation.png
    - assets/fragile.png
    - assets/deception.png
    - assets/resilience.png
    - assets/chaos.png
    - assets/eternity.png
    - assets/conscience.png
    - assets/capitol.png
    - assets/moloM.png
    - assets/esplanade.png
    - assets/megaworld.png
    - assets/calle.png
    - assets/batchoy.png
    - assets/pancitM.png
    - assets/kbl.png
    - assets/seafood.png
    - assets/streetF.png
    - assets/biscuit.png
    - assets/bokujuice.png
    - assets/moloC.png
    - assets/miagaoC.png
    - assets/garinF.png
    - assets/market.png
    - assets/isla.png
    - assets/cpic.png
    - assets/cpic2.png
    - assets/cpic3.png
    - assets/cpic4.png
    - assets/iconh.png
    - assets/owl.png
    - assets/dictionary.json
    - assets/owl_fly.riv
    - assets/fire.png
    - assets/water-drop.png
    - assets/candle.png
    - assets/mirror.png
    - assets/road.png
    - assets/rainbow.png
    - assets/earth.png
    - assets/sky.png
    - assets/beach.png
    - assets/stone.png
    - assets/smoke.png
    - assets/rope.png
    - assets/basket.png
    - assets/hammer.png
    - assets/fan2.png
    - assets/milk.png
    - assets/shirt.png
    - assets/freedom.png
    - assets/truth.png
    - assets/courage.png
    - assets/justice.png
    - assets/hope.png
    - assets/faith.png
    - assets/destiny.png
    - assets/sacrifice.png
    - assets/forgiveness.png
    - assets/silence.png
    - assets/fear.png
    - assets/anger.png
    - assets/gratitude.png
    - assets/promise.png
    - assets/chair.png
    - assets/table.png
    - assets/watch.png
    - assets/bag.png
    - assets/pen.png
    - assets/paper.png
    - assets/water.png
    - assets/juice.png
    - assets/coffee.png
    - assets/banana.png
    - assets/mango.png
    - assets/grape.png
    - assets/apple.png
    - assets/school.png
    - assets/church.png
    - assets/run.png
    - assets/sleep.png
    - assets/walk.png
    - assets/eat.png
    - assets/drink.png
    - assets/swim.png
    - assets/read.png
    - assets/dance.png
    - assets/write.png
    - assets/draw.png
    - assets/sing.png
    - assets/paint.png
    - assets/talk.png
    - assets/jump.png
    - assets/sit.png
    - assets/stand.png
    - assets/no.png
    - assets/go.png
    - assets/stop.png
    - assets/yes.png
    - assets/maybe.png
    - assets/breathe.png
    - assets/grow.png
    - assets/brush.png
    - assets/bathe.png
    - assets/washface.png
    - assets/rice.png
    - assets/bread.png
    - assets/fork.png
    - assets/plate.png
    - assets/spoon.png
    - assets/glass.png
    - assets/knife.png
    - assets/calendar.png
    - assets/eraser.png
    - assets/notebook.png
    - assets/soda.png
    - assets/pray.png
    - assets/pencil.png
    - assets/cup.png
    - assets/teacher.png
    - assets/doctor.png
    - assets/carpenter.png
    - assets/nurse.png
    - assets/markets.png
    - assets/police.png
    - assets/soldier.png
    - assets/fireman.png
    - assets/fisherman.png
    - assets/driver.png
    - assets/cook.png
    - assets/tailor.png
    - assets/painter.png
    - assets/reader.png
    - assets/writer.png
    - assets/singer.png
    - assets/dancer.png
    - assets/actor.png
    - assets/gardener.png
    - assets/butcher.png
    - assets/barber.png
    - assets/vendor.png
    - assets/cleaner.png
    - assets/loader.png
    - assets/deliverer.png
    - assets/washer.png
    - assets/bather.png
    - assets/housepainter.png
    - assets/resident.png
    - assets/traveler.png
    - assets/visitor.png
    - assets/students.png
    - assets/elephant.png
    - assets/goat.png
    - assets/cow.png
    - assets/duck.png
    - assets/tomato.png
    - assets/pineapple.png
    - assets/helicopter.png
    - assets/tiger.png
    - assets/monkey.png
    - assets/crocodile.png
    - assets/snake.png
    - assets/papaya.png
    - assets/coconut.png
    - assets/motorbike.png
    - assets/tricycle.png
    - assets/happiness.png
    - assets/sad.png
    - assets/angry.png
    - assets/life.png
    - assets/death.png
    - assets/lies.png
    - assets/success.png
    - assets/failure.png
    - assets/forbidden.png
    - assets/wave.png
    - assets/innovation.png
    - assets/fog.png
    

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/Starting.png
