// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnoudzqn6bRpOV_VM3tBZyFq4XltWv8jY',
    appId: '1:120192913600:web:c715056389d8d922d31d25',
    messagingSenderId: '120192913600',
    projectId: 'hilingo-b5e9d',
    authDomain: 'hilingo-b5e9d.firebaseapp.com',
    storageBucket: 'hilingo-b5e9d.firebasestorage.app',
    measurementId: 'G-RYXMRRB00R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmjhZKMKWIUEERjWj07HIjXEnMEBmO298',
    appId: '1:120192913600:android:975f09f1b1c02577d31d25',
    messagingSenderId: '120192913600',
    projectId: 'hilingo-b5e9d',
    storageBucket: 'hilingo-b5e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5V2RBafOtZd3VW_LtWgi3KPuPhwa4I20',
    appId: '1:120192913600:ios:3703741ae7039cb5d31d25',
    messagingSenderId: '120192913600',
    projectId: 'hilingo-b5e9d',
    storageBucket: 'hilingo-b5e9d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5V2RBafOtZd3VW_LtWgi3KPuPhwa4I20',
    appId: '1:120192913600:ios:3703741ae7039cb5d31d25',
    messagingSenderId: '120192913600',
    projectId: 'hilingo-b5e9d',
    storageBucket: 'hilingo-b5e9d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnoudzqn6bRpOV_VM3tBZyFq4XltWv8jY',
    appId: '1:120192913600:web:2bd6f9ab218b71c5d31d25',
    messagingSenderId: '120192913600',
    projectId: 'hilingo-b5e9d',
    authDomain: 'hilingo-b5e9d.firebaseapp.com',
    storageBucket: 'hilingo-b5e9d.firebasestorage.app',
    measurementId: 'G-MPL9RCJ1F2',
  );
}
